import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:package_info_plus/package_info_plus.dart';

import '../utils/web_version.dart';

/// Provides version information from a single source (pubspec.yaml).
///
/// Strips trailing `.0` from the semantic version for cleaner user-facing
/// display (e.g. `1.6.0` → `1.6`).
///
/// On web, if `package_info_plus` fails to load (MissingPluginException),
/// falls back to reading `version.json` generated by flutter build web,
/// or compile-time constants injected by Flutter.
class VersionService {
  final String _version;
  final String _buildNumber;

  VersionService._(this._version, this._buildNumber);

  /// Compile-time constants injected by Flutter from pubspec.yaml.
  /// Available on all platforms — no manual updates needed.
  static const _buildName = String.fromEnvironment('FLUTTER_BUILD_NAME');
  static const _buildNum = String.fromEnvironment('FLUTTER_BUILD_NUMBER');

  static Future<VersionService> init() async {
    try {
      final info = await PackageInfo.fromPlatform();
      return VersionService._(info.version, info.buildNumber);
    } catch (e) {
      debugPrint('VersionService: package_info_plus failed, attempting fallback — $e');
      
      // Try fetching version.json (works on web)
      final webVersion = await readWebVersionJson();
      if (webVersion != null) {
         return VersionService._(
           webVersion['version'] ?? 'unknown', 
           webVersion['build_number'] ?? '0'
         );
      }

      // Final fallback to compile-time definitions (works on native, not web)
      return VersionService._(
        _buildName.isNotEmpty ? _buildName : 'unknown',
        _buildNum.isNotEmpty ? _buildNum : '0',
      );
    }
  }

  /// Semantic version with trailing `.0` stripped (e.g. `1.6`).
  String get appVersion => _stripTrailingZero(_version);

  /// Build number string (e.g. `25`).
  String get buildNumber => _buildNumber;

  /// User-facing full version string (e.g. `v1.6+25`).
  String get fullVersion => 'v$appVersion+$buildNumber';

  /// Strips a single trailing `.0` from a version string.
  /// `1.6.0` → `1.6`, but `1.0.0` → `1.0`.
  String _stripTrailingZero(String version) {
    if (version.endsWith('.0')) {
      return version.substring(0, version.length - 2);
    }
    return version;
  }
}

/// Async provider for version information.
final versionServiceProvider = FutureProvider<VersionService>((ref) async {
  return VersionService.init();
});
