// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhu2AyyhYHCPd3QhZsGB70aydVqmDWJwE',
    appId: '1:522467216661:web:74f6ef27a9bbd31e7c6d1c',
    messagingSenderId: '522467216661',
    projectId: 'scrolllit',
    authDomain: 'scrolllit.firebaseapp.com',
    storageBucket: 'scrolllit.firebasestorage.app',
    measurementId: 'G-KEB54XXBHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDmpnO8zW5-hORClzAIh7s-l_l_p1AEXs',
    appId: '1:522467216661:android:0d11d3ca471f055f7c6d1c',
    messagingSenderId: '522467216661',
    projectId: 'scrolllit',
    storageBucket: 'scrolllit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfn2w519S5nj4ZB9OaDNbvaEXAwu3z2Sk',
    appId: '1:522467216661:ios:5443718c47970c437c6d1c',
    messagingSenderId: '522467216661',
    projectId: 'scrolllit',
    storageBucket: 'scrolllit.firebasestorage.app',
    iosBundleId: 'com.scrollit.scrollit',
  );
}
